target/release/onedrive-sync-daemon usr/bin/
target/release/onedrive-sync-ui usr/bin/
target/release/onedrive-sync-applet usr/bin/
debian/com.github.bmideas.onedrive-sync.desktop usr/share/applications/
debian/com.github.bmideas.onedrive-sync-applet.desktop usr/share/applications/
debian/onedrive-sync-daemon.desktop usr/share/applications/
resources/programfiles/open-onedrive.svg usr/share/icons/hicolor/scalable/apps/
ui/resources/icons/hicolor/scalable/apps/icon.svg usr/share/icons/hicolor/scalable/apps/
resources/programfiles/icons usr/share/icons/hicolor
resources/programfiles/onedrive-sync.xml usr/share/mime/packages/
debian/onedrive-sync.service etc/systemd/user/

